// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAddresses = `-- name: CountAddresses :one
SELECT COUNT(*) FROM addresses WHERE subnet_id = ?
`

func (q *Queries) CountAddresses(ctx context.Context, subnetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAddresses, subnetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAddressesByStatus = `-- name: CountAddressesByStatus :one
SELECT COUNT(*) FROM addresses WHERE subnet_id = ? AND status = ?
`

type CountAddressesByStatusParams struct {
	SubnetID int64  `json:"subnet_id"`
	Status   string `json:"status"`
}

func (q *Queries) CountAddressesByStatus(ctx context.Context, arg CountAddressesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAddressesByStatus, arg.SubnetID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :execresult
INSERT INTO addresses (subnet_id, ip, ip_text, hostname, mac, description, status, tag_id, is_gateway, device_id, device_port, owner)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAddressParams struct {
	SubnetID    int64          `json:"subnet_id"`
	Ip          []byte         `json:"ip"`
	IpText      string         `json:"ip_text"`
	Hostname    string         `json:"hostname"`
	Mac         string         `json:"mac"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	TagID       sql.NullInt64  `json:"tag_id"`
	IsGateway   bool           `json:"is_gateway"`
	DeviceID    sql.NullInt64  `json:"device_id"`
	DevicePort  string         `json:"device_port"`
	Owner       string         `json:"owner"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAddress,
		arg.SubnetID,
		arg.Ip,
		arg.IpText,
		arg.Hostname,
		arg.Mac,
		arg.Description,
		arg.Status,
		arg.TagID,
		arg.IsGateway,
		arg.DeviceID,
		arg.DevicePort,
		arg.Owner,
	)
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = ?
`

func (q *Queries) DeleteAddress(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, subnet_id, ip, ip_text, hostname, mac, description, status, tag_id, is_gateway, device_id, device_port, owner, last_seen_at, dns_checked_at, created_at, updated_at
FROM addresses
WHERE id = ?
`

func (q *Queries) GetAddressByID(ctx context.Context, id int64) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.SubnetID,
		&i.Ip,
		&i.IpText,
		&i.Hostname,
		&i.Mac,
		&i.Description,
		&i.Status,
		&i.TagID,
		&i.IsGateway,
		&i.DeviceID,
		&i.DevicePort,
		&i.Owner,
		&i.LastSeenAt,
		&i.DnsCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByIP = `-- name: GetAddressByIP :one
SELECT id, subnet_id, ip, ip_text, hostname, mac, description, status, tag_id, is_gateway, device_id, device_port, owner, last_seen_at, dns_checked_at, created_at, updated_at
FROM addresses
WHERE subnet_id = ? AND ip = ?
`

type GetAddressByIPParams struct {
	SubnetID int64  `json:"subnet_id"`
	Ip       []byte `json:"ip"`
}

func (q *Queries) GetAddressByIP(ctx context.Context, arg GetAddressByIPParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByIP, arg.SubnetID, arg.Ip)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.SubnetID,
		&i.Ip,
		&i.IpText,
		&i.Hostname,
		&i.Mac,
		&i.Description,
		&i.Status,
		&i.TagID,
		&i.IsGateway,
		&i.DeviceID,
		&i.DevicePort,
		&i.Owner,
		&i.LastSeenAt,
		&i.DnsCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByIPText = `-- name: GetAddressByIPText :one
SELECT id, subnet_id, ip, ip_text, hostname, mac, description, status, tag_id, is_gateway, device_id, device_port, owner, last_seen_at, dns_checked_at, created_at, updated_at
FROM addresses
WHERE subnet_id = ? AND ip_text = ?
`

type GetAddressByIPTextParams struct {
	SubnetID int64  `json:"subnet_id"`
	IpText   string `json:"ip_text"`
}

func (q *Queries) GetAddressByIPText(ctx context.Context, arg GetAddressByIPTextParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByIPText, arg.SubnetID, arg.IpText)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.SubnetID,
		&i.Ip,
		&i.IpText,
		&i.Hostname,
		&i.Mac,
		&i.Description,
		&i.Status,
		&i.TagID,
		&i.IsGateway,
		&i.DeviceID,
		&i.DevicePort,
		&i.Owner,
		&i.LastSeenAt,
		&i.DnsCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressIPsBySubnet = `-- name: ListAddressIPsBySubnet :many
SELECT ip_text FROM addresses WHERE subnet_id = ?
`

func (q *Queries) ListAddressIPsBySubnet(ctx context.Context, subnetID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAddressIPsBySubnet, subnetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ip_text string
		if err := rows.Scan(&ip_text); err != nil {
			return nil, err
		}
		items = append(items, ip_text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, subnet_id, ip, ip_text, hostname, mac, description, status, tag_id, is_gateway, device_id, device_port, owner, last_seen_at, dns_checked_at, created_at, updated_at
FROM addresses
WHERE subnet_id = ?
ORDER BY ip
LIMIT ? OFFSET ?
`

type ListAddressesParams struct {
	SubnetID int64 `json:"subnet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, listAddresses, arg.SubnetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.SubnetID,
			&i.Ip,
			&i.IpText,
			&i.Hostname,
			&i.Mac,
			&i.Description,
			&i.Status,
			&i.TagID,
			&i.IsGateway,
			&i.DeviceID,
			&i.DevicePort,
			&i.Owner,
			&i.LastSeenAt,
			&i.DnsCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE addresses
SET hostname = ?, mac = ?, description = ?, status = ?, tag_id = ?, is_gateway = ?, device_id = ?, device_port = ?, owner = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAddressParams struct {
	Hostname    string         `json:"hostname"`
	Mac         string         `json:"mac"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	TagID       sql.NullInt64  `json:"tag_id"`
	IsGateway   bool           `json:"is_gateway"`
	DeviceID    sql.NullInt64  `json:"device_id"`
	DevicePort  string         `json:"device_port"`
	Owner       string         `json:"owner"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateAddress,
		arg.Hostname,
		arg.Mac,
		arg.Description,
		arg.Status,
		arg.TagID,
		arg.IsGateway,
		arg.DeviceID,
		arg.DevicePort,
		arg.Owner,
		arg.ID,
	)
	return err
}
