// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :execresult
INSERT INTO audit_logs (actor_id, action, resource_type, resource_id, before_json, after_json, ip, user_agent, request_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	ActorID      sql.NullInt64  `json:"actor_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   int64          `json:"resource_id"`
	BeforeJson   sql.NullString `json:"before_json"`
	AfterJson    sql.NullString `json:"after_json"`
	Ip           string         `json:"ip"`
	UserAgent    string         `json:"user_agent"`
	RequestID    string         `json:"request_id"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
	)
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, resource_type, resource_id, before_json, after_json, ip, user_agent, request_id, created_at FROM audit_logs ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
