// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAPIToken = `-- name: CreateAPIToken :execresult
INSERT INTO api_tokens (name, token_hash, user_id, permissions, expires_at, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAPITokenParams struct {
	Name        string         `json:"name"`
	TokenHash   string         `json:"token_hash"`
	UserID      int64          `json:"user_id"`
	Permissions sql.NullString `json:"permissions"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAPIToken,
		arg.Name,
		arg.TokenHash,
		arg.UserID,
		arg.Permissions,
		arg.ExpiresAt,
		arg.Status,
	)
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = ?
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, id)
	return err
}

const deleteResourcePermission = `-- name: DeleteResourcePermission :exec
DELETE FROM resource_permissions WHERE id = ?
`

func (q *Queries) DeleteResourcePermission(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResourcePermission, id)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, name, token_hash, user_id, permissions, expires_at, last_used_at, status, created_at, updated_at
FROM api_tokens
WHERE token_hash = ?
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.UserID,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourcePermissions = `-- name: GetResourcePermissions :many
SELECT id, user_id, group_id, resource_type, resource_id, permission_level, created_at, updated_at
FROM resource_permissions
WHERE resource_type = ? AND resource_id = ?
`

type GetResourcePermissionsParams struct {
	ResourceType string `json:"resource_type"`
	ResourceID   int64  `json:"resource_id"`
}

func (q *Queries) GetResourcePermissions(ctx context.Context, arg GetResourcePermissionsParams) ([]ResourcePermission, error) {
	rows, err := q.db.QueryContext(ctx, getResourcePermissions, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourcePermission{}
	for rows.Next() {
		var i ResourcePermission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.ResourceType,
			&i.ResourceID,
			&i.PermissionLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserResourcePermissions = `-- name: GetUserResourcePermissions :many
SELECT id, user_id, group_id, resource_type, resource_id, permission_level, created_at, updated_at
FROM resource_permissions
WHERE user_id = ?
`

func (q *Queries) GetUserResourcePermissions(ctx context.Context, userID sql.NullInt64) ([]ResourcePermission, error) {
	rows, err := q.db.QueryContext(ctx, getUserResourcePermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourcePermission{}
	for rows.Next() {
		var i ResourcePermission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.ResourceType,
			&i.ResourceID,
			&i.PermissionLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, user_id, permissions, expires_at, last_used_at, status, created_at, updated_at
FROM api_tokens
WHERE user_id = ?
ORDER BY id
`

type ListAPITokensRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	UserID      int64          `json:"user_id"`
	Permissions sql.NullString `json:"permissions"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	LastUsedAt  sql.NullTime   `json:"last_used_at"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ListAPITokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResourcePermission = `-- name: SetResourcePermission :execresult
INSERT INTO resource_permissions (user_id, group_id, resource_type, resource_id, permission_level)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE permission_level = VALUES(permission_level), updated_at = CURRENT_TIMESTAMP
`

type SetResourcePermissionParams struct {
	UserID          sql.NullInt64 `json:"user_id"`
	GroupID         sql.NullInt64 `json:"group_id"`
	ResourceType    string        `json:"resource_type"`
	ResourceID      int64         `json:"resource_id"`
	PermissionLevel string        `json:"permission_level"`
}

func (q *Queries) SetResourcePermission(ctx context.Context, arg SetResourcePermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setResourcePermission,
		arg.UserID,
		arg.GroupID,
		arg.ResourceType,
		arg.ResourceID,
		arg.PermissionLevel,
	)
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
	return err
}

const updateAPITokenStatus = `-- name: UpdateAPITokenStatus :exec
UPDATE api_tokens
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAPITokenStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAPITokenStatus(ctx context.Context, arg UpdateAPITokenStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenStatus, arg.Status, arg.ID)
	return err
}
