// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :execresult
INSERT INTO devices (name, hostname, mgmt_ip, type_id, location_id, rack_id, rack_start_u, rack_size_u, manufacturer, model, serial_number, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	Name         string         `json:"name"`
	Hostname     string         `json:"hostname"`
	MgmtIp       string         `json:"mgmt_ip"`
	TypeID       sql.NullInt64  `json:"type_id"`
	LocationID   sql.NullInt64  `json:"location_id"`
	RackID       sql.NullInt64  `json:"rack_id"`
	RackStartU   sql.NullInt32  `json:"rack_start_u"`
	RackSizeU    sql.NullInt32  `json:"rack_size_u"`
	Manufacturer string         `json:"manufacturer"`
	Model        string         `json:"model"`
	SerialNumber string         `json:"serial_number"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDevice,
		arg.Name,
		arg.Hostname,
		arg.MgmtIp,
		arg.TypeID,
		arg.LocationID,
		arg.RackID,
		arg.RackStartU,
		arg.RackSizeU,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNumber,
		arg.Description,
	)
}

const createDeviceType = `-- name: CreateDeviceType :execresult
INSERT INTO device_types (name, icon, description) VALUES (?, ?, ?)
`

type CreateDeviceTypeParams struct {
	Name        string         `json:"name"`
	Icon        string         `json:"icon"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateDeviceType(ctx context.Context, arg CreateDeviceTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDeviceType, arg.Name, arg.Icon, arg.Description)
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const deleteDeviceType = `-- name: DeleteDeviceType :exec
DELETE FROM device_types WHERE id = ?
`

func (q *Queries) DeleteDeviceType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceType, id)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, name, hostname, mgmt_ip, type_id, location_id, rack_id, rack_start_u, rack_size_u, manufacturer, model, serial_number, description, created_at, updated_at FROM devices WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.MgmtIp,
		&i.TypeID,
		&i.LocationID,
		&i.RackID,
		&i.RackStartU,
		&i.RackSizeU,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTypeByID = `-- name: GetDeviceTypeByID :one
SELECT id, name, icon, description, created_at, updated_at FROM device_types WHERE id = ?
`

func (q *Queries) GetDeviceTypeByID(ctx context.Context, id int64) (DeviceType, error) {
	row := q.db.QueryRowContext(ctx, getDeviceTypeByID, id)
	var i DeviceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceTypes = `-- name: ListDeviceTypes :many
SELECT id, name, icon, description, created_at, updated_at FROM device_types ORDER BY name
`

func (q *Queries) ListDeviceTypes(ctx context.Context) ([]DeviceType, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceType{}
	for rows.Next() {
		var i DeviceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, hostname, mgmt_ip, type_id, location_id, rack_id, rack_start_u, rack_size_u, manufacturer, model, serial_number, description, created_at, updated_at FROM devices ORDER BY name LIMIT ? OFFSET ?
`

type ListDevicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.MgmtIp,
			&i.TypeID,
			&i.LocationID,
			&i.RackID,
			&i.RackStartU,
			&i.RackSizeU,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNumber,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices SET name = ?, hostname = ?, mgmt_ip = ?, type_id = ?, location_id = ?, rack_id = ?, rack_start_u = ?, rack_size_u = ?, manufacturer = ?, model = ?, serial_number = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateDeviceParams struct {
	Name         string         `json:"name"`
	Hostname     string         `json:"hostname"`
	MgmtIp       string         `json:"mgmt_ip"`
	TypeID       sql.NullInt64  `json:"type_id"`
	LocationID   sql.NullInt64  `json:"location_id"`
	RackID       sql.NullInt64  `json:"rack_id"`
	RackStartU   sql.NullInt32  `json:"rack_start_u"`
	RackSizeU    sql.NullInt32  `json:"rack_size_u"`
	Manufacturer string         `json:"manufacturer"`
	Model        string         `json:"model"`
	SerialNumber string         `json:"serial_number"`
	Description  sql.NullString `json:"description"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Name,
		arg.Hostname,
		arg.MgmtIp,
		arg.TypeID,
		arg.LocationID,
		arg.RackID,
		arg.RackStartU,
		arg.RackSizeU,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNumber,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateDeviceType = `-- name: UpdateDeviceType :exec
UPDATE device_types SET name = ?, icon = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateDeviceTypeParams struct {
	Name        string         `json:"name"`
	Icon        string         `json:"icon"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceType,
		arg.Name,
		arg.Icon,
		arg.Description,
		arg.ID,
	)
	return err
}
