// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countFolders = `-- name: CountFolders :one
SELECT COUNT(*) FROM folders WHERE section_id = ?
`

func (q *Queries) CountFolders(ctx context.Context, sectionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFolders, sectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :execresult
INSERT INTO folders (section_id, parent_id, name, description, sort_order)
VALUES (?, ?, ?, ?, ?)
`

type CreateFolderParams struct {
	SectionID   int64          `json:"section_id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFolder,
		arg.SectionID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ?
`

func (q *Queries) DeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, id)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, section_id, parent_id, name, description, sort_order, created_at, updated_at
FROM folders
WHERE id = ?
`

func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubFolders = `-- name: GetSubFolders :many
SELECT id, section_id, parent_id, name, description, sort_order, created_at, updated_at
FROM folders
WHERE parent_id = ?
ORDER BY sort_order, name
`

func (q *Queries) GetSubFolders(ctx context.Context, parentID sql.NullInt64) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, getSubFolders, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, section_id, parent_id, name, description, sort_order, created_at, updated_at
FROM folders
WHERE section_id = ?
ORDER BY sort_order, name
LIMIT ? OFFSET ?
`

type ListFoldersParams struct {
	SectionID int64 `json:"section_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders, arg.SectionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :exec
UPDATE folders
SET name = ?, description = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateFolderParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int32          `json:"sort_order"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) error {
	_, err := q.db.ExecContext(ctx, updateFolder,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
