// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addGroupRole = `-- name: AddGroupRole :exec
INSERT INTO group_roles (group_id, role_id)
VALUES (?, ?)
`

type AddGroupRoleParams struct {
	GroupID int64 `json:"group_id"`
	RoleID  int64 `json:"role_id"`
}

func (q *Queries) AddGroupRole(ctx context.Context, arg AddGroupRoleParams) error {
	_, err := q.db.ExecContext(ctx, addGroupRole, arg.GroupID, arg.RoleID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups (user_id, group_id)
VALUES (?, ?)
`

type AddUserToGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :execresult
INSERT INTO ` + "`" + `groups` + "`" + ` (name, description)
VALUES (?, ?)
`

type CreateGroupParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGroup, arg.Name, arg.Description)
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM ` + "`" + `groups` + "`" + ` WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, created_at, updated_at
FROM ` + "`" + `groups` + "`" + `
WHERE id = ?
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupRoles = `-- name: GetGroupRoles :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at
FROM roles r
JOIN group_roles gr ON gr.role_id = r.id
WHERE gr.group_id = ?
`

func (q *Queries) GetGroupRoles(ctx context.Context, groupID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getGroupRoles, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.description, g.created_at, g.updated_at
FROM ` + "`" + `groups` + "`" + ` g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = ?
`

func (q *Queries) GetUserGroups(ctx context.Context, userID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, created_at, updated_at
FROM ` + "`" + `groups` + "`" + `
ORDER BY id
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupRole = `-- name: RemoveGroupRole :exec
DELETE FROM group_roles WHERE group_id = ? AND role_id = ?
`

type RemoveGroupRoleParams struct {
	GroupID int64 `json:"group_id"`
	RoleID  int64 `json:"role_id"`
}

func (q *Queries) RemoveGroupRole(ctx context.Context, arg RemoveGroupRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupRole, arg.GroupID, arg.RoleID)
	return err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_groups WHERE user_id = ? AND group_id = ?
`

type RemoveUserFromGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE ` + "`" + `groups` + "`" + `
SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateGroupParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.Name, arg.Description, arg.ID)
	return err
}
