// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAllRacks = `-- name: CountAllRacks :one
SELECT COUNT(*) FROM racks
`

func (q *Queries) CountAllRacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllRacks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLocations = `-- name: CountLocations :one
SELECT COUNT(*) FROM locations
`

func (q *Queries) CountLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRacks = `-- name: CountRacks :one
SELECT COUNT(*) FROM racks WHERE location_id = ?
`

func (q *Queries) CountRacks(ctx context.Context, locationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRacks, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :execresult
INSERT INTO locations (name, address, room, row_name, description) VALUES (?, ?, ?, ?, ?)
`

type CreateLocationParams struct {
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	Room        string         `json:"room"`
	RowName     string         `json:"row_name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLocation,
		arg.Name,
		arg.Address,
		arg.Room,
		arg.RowName,
		arg.Description,
	)
}

const createRack = `-- name: CreateRack :execresult
INSERT INTO racks (location_id, name, size_u, row_name, position, direction, description) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRackParams struct {
	LocationID  int64          `json:"location_id"`
	Name        string         `json:"name"`
	SizeU       int32          `json:"size_u"`
	RowName     string         `json:"row_name"`
	Position    string         `json:"position"`
	Direction   string         `json:"direction"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRack(ctx context.Context, arg CreateRackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRack,
		arg.LocationID,
		arg.Name,
		arg.SizeU,
		arg.RowName,
		arg.Position,
		arg.Direction,
		arg.Description,
	)
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = ?
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLocation, id)
	return err
}

const deleteRack = `-- name: DeleteRack :exec
DELETE FROM racks WHERE id = ?
`

func (q *Queries) DeleteRack(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRack, id)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, address, room, row_name, description, created_at, updated_at FROM locations WHERE id = ?
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Room,
		&i.RowName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRackByID = `-- name: GetRackByID :one
SELECT id, location_id, name, size_u, row_name, position, direction, description, created_at, updated_at FROM racks WHERE id = ?
`

func (q *Queries) GetRackByID(ctx context.Context, id int64) (Rack, error) {
	row := q.db.QueryRowContext(ctx, getRackByID, id)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.SizeU,
		&i.RowName,
		&i.Position,
		&i.Direction,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, address, room, row_name, description, created_at, updated_at FROM locations ORDER BY name LIMIT ? OFFSET ?
`

type ListLocationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Room,
			&i.RowName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRacks = `-- name: ListAllRacks :many
SELECT id, location_id, name, size_u, row_name, position, direction, description, created_at, updated_at FROM racks ORDER BY name LIMIT ? OFFSET ?
`

type ListAllRacksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllRacks(ctx context.Context, arg ListAllRacksParams) ([]Rack, error) {
	rows, err := q.db.QueryContext(ctx, listAllRacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rack{}
	for rows.Next() {
		var i Rack
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.SizeU,
			&i.RowName,
			&i.Position,
			&i.Direction,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacks = `-- name: ListRacks :many
SELECT id, location_id, name, size_u, row_name, position, direction, description, created_at, updated_at FROM racks WHERE location_id = ? ORDER BY name LIMIT ? OFFSET ?
`

type ListRacksParams struct {
	LocationID int64 `json:"location_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListRacks(ctx context.Context, arg ListRacksParams) ([]Rack, error) {
	rows, err := q.db.QueryContext(ctx, listRacks, arg.LocationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rack{}
	for rows.Next() {
		var i Rack
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.SizeU,
			&i.RowName,
			&i.Position,
			&i.Direction,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :exec
UPDATE locations SET name = ?, address = ?, room = ?, row_name = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateLocationParams struct {
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	Room        string         `json:"room"`
	RowName     string         `json:"row_name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) error {
	_, err := q.db.ExecContext(ctx, updateLocation,
		arg.Name,
		arg.Address,
		arg.Room,
		arg.RowName,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateRack = `-- name: UpdateRack :exec
UPDATE racks SET name = ?, size_u = ?, row_name = ?, position = ?, direction = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRackParams struct {
	Name        string         `json:"name"`
	SizeU       int32          `json:"size_u"`
	RowName     string         `json:"row_name"`
	Position    string         `json:"position"`
	Direction   string         `json:"direction"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateRack(ctx context.Context, arg UpdateRackParams) error {
	_, err := q.db.ExecContext(ctx, updateRack,
		arg.Name,
		arg.SizeU,
		arg.RowName,
		arg.Position,
		arg.Direction,
		arg.Description,
		arg.ID,
	)
	return err
}
