// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Address struct {
	ID           int64          `json:"id"`
	SubnetID     int64          `json:"subnet_id"`
	Ip           []byte         `json:"ip"`
	IpText       string         `json:"ip_text"`
	Hostname     string         `json:"hostname"`
	Mac          string         `json:"mac"`
	Description  sql.NullString `json:"description"`
	Status       string         `json:"status"`
	TagID        sql.NullInt64  `json:"tag_id"`
	IsGateway    bool           `json:"is_gateway"`
	DeviceID     sql.NullInt64  `json:"device_id"`
	DevicePort   string         `json:"device_port"`
	Owner        string         `json:"owner"`
	LastSeenAt   sql.NullTime   `json:"last_seen_at"`
	DnsCheckedAt sql.NullTime   `json:"dns_checked_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type ApiToken struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	TokenHash   string         `json:"token_hash"`
	UserID      int64          `json:"user_id"`
	Permissions sql.NullString `json:"permissions"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	LastUsedAt  sql.NullTime   `json:"last_used_at"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type AuditLog struct {
	ID           int64          `json:"id"`
	ActorID      sql.NullInt64  `json:"actor_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   int64          `json:"resource_id"`
	BeforeJson   sql.NullString `json:"before_json"`
	AfterJson    sql.NullString `json:"after_json"`
	Ip           string         `json:"ip"`
	UserAgent    string         `json:"user_agent"`
	RequestID    string         `json:"request_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Device struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Hostname     string         `json:"hostname"`
	MgmtIp       string         `json:"mgmt_ip"`
	TypeID       sql.NullInt64  `json:"type_id"`
	LocationID   sql.NullInt64  `json:"location_id"`
	RackID       sql.NullInt64  `json:"rack_id"`
	RackStartU   sql.NullInt32  `json:"rack_start_u"`
	RackSizeU    sql.NullInt32  `json:"rack_size_u"`
	Manufacturer string         `json:"manufacturer"`
	Model        string         `json:"model"`
	SerialNumber string         `json:"serial_number"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type DeviceType struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Icon        string         `json:"icon"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Folder struct {
	ID          int64          `json:"id"`
	SectionID   int64          `json:"section_id"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int32          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Group struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type GroupRole struct {
	ID        int64     `json:"id"`
	GroupID   int64     `json:"group_id"`
	RoleID    int64     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type IpRequest struct {
	ID             int64          `json:"id"`
	SubnetID       int64          `json:"subnet_id"`
	ApplicantID    int64          `json:"applicant_id"`
	RequestedIp    string         `json:"requested_ip"`
	Hostname       string         `json:"hostname"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	ApproverID     sql.NullInt64  `json:"approver_id"`
	ApproveComment sql.NullString `json:"approve_comment"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type L2Domain struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Location struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	Room        string         `json:"room"`
	RowName     string         `json:"row_name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Nameserver struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Server      string         `json:"server"`
	Port        int32          `json:"port"`
	TimeoutMs   int32          `json:"timeout_ms"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Nat struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Type             string         `json:"type"`
	InsideAddressID  sql.NullInt64  `json:"inside_address_id"`
	OutsideAddressID sql.NullInt64  `json:"outside_address_id"`
	InsideIp         string         `json:"inside_ip"`
	OutsideIp        string         `json:"outside_ip"`
	InsidePort       sql.NullInt32  `json:"inside_port"`
	OutsidePort      sql.NullInt32  `json:"outside_port"`
	Protocol         string         `json:"protocol"`
	DeviceID         sql.NullInt64  `json:"device_id"`
	Description      sql.NullString `json:"description"`
	Enabled          bool           `json:"enabled"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Permission struct {
	ID          int64          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Rack struct {
	ID          int64          `json:"id"`
	LocationID  int64          `json:"location_id"`
	Name        string         `json:"name"`
	SizeU       int32          `json:"size_u"`
	RowName     string         `json:"row_name"`
	Position    string         `json:"position"`
	Direction   string         `json:"direction"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ResourcePermission struct {
	ID              int64         `json:"id"`
	UserID          sql.NullInt64 `json:"user_id"`
	GroupID         sql.NullInt64 `json:"group_id"`
	ResourceType    string        `json:"resource_type"`
	ResourceID      int64         `json:"resource_id"`
	PermissionLevel string        `json:"permission_level"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RolePermission struct {
	ID           int64     `json:"id"`
	RoleID       int64     `json:"role_id"`
	PermissionID int64     `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type ScanResult struct {
	ID        int64          `json:"id"`
	TaskID    int64          `json:"task_id"`
	IpText    string         `json:"ip_text"`
	Status    string         `json:"status"`
	Message   sql.NullString `json:"message"`
	CreatedAt time.Time      `json:"created_at"`
}

type ScanTask struct {
	ID         int64          `json:"id"`
	SubnetID   int64          `json:"subnet_id"`
	TaskType   string         `json:"task_type"`
	Status     string         `json:"status"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
	TotalCount int32          `json:"total_count"`
	AliveCount int32          `json:"alive_count"`
	NewCount   int32          `json:"new_count"`
	Error      sql.NullString `json:"error"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Section struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	StrictMode  bool           `json:"strict_mode"`
	ShowVlan    bool           `json:"show_vlan"`
	ShowVrf     bool           `json:"show_vrf"`
	SubnetOrder string         `json:"subnet_order"`
	SortOrder   int32          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Subnet struct {
	ID               int64          `json:"id"`
	SectionID        int64          `json:"section_id"`
	ParentID         sql.NullInt64  `json:"parent_id"`
	Cidr             string         `json:"cidr"`
	IpVersion        uint8          `json:"ip_version"`
	Network          []byte         `json:"network"`
	PrefixLen        uint8          `json:"prefix_len"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	VlanID           sql.NullInt64  `json:"vlan_id"`
	VrfID            sql.NullInt64  `json:"vrf_id"`
	LocationID       sql.NullInt64  `json:"location_id"`
	NameserverID     sql.NullInt64  `json:"nameserver_id"`
	ScanEnabled      bool           `json:"scan_enabled"`
	DiscoverEnabled  bool           `json:"discover_enabled"`
	ThresholdPercent int32          `json:"threshold_percent"`
	AllowRequest     bool           `json:"allow_request"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type SystemSetting struct {
	ID        int64          `json:"id"`
	Category  string         `json:"category"`
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID               int64        `json:"id"`
	Username         string       `json:"username"`
	PasswordHash     string       `json:"password_hash"`
	DisplayName      string       `json:"display_name"`
	Email            string       `json:"email"`
	Status           string       `json:"status"`
	FailedLoginCount int32        `json:"failed_login_count"`
	LockedUntil      sql.NullTime `json:"locked_until"`
	LastLoginAt      sql.NullTime `json:"last_login_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

type UserGroup struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	GroupID   int64     `json:"group_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserRole struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	RoleID    int64     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Vlan struct {
	ID          int64          `json:"id"`
	L2DomainID  sql.NullInt64  `json:"l2_domain_id"`
	VlanID      int32          `json:"vlan_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Vrf struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Rd          string         `json:"rd"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
