// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nameservers.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countNameservers = `-- name: CountNameservers :one
SELECT COUNT(*) FROM nameservers
`

func (q *Queries) CountNameservers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNameservers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNameserver = `-- name: CreateNameserver :execresult
INSERT INTO nameservers (name, type, server, port, timeout_ms, enabled, description) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateNameserverParams struct {
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Server      string         `json:"server"`
	Port        int32          `json:"port"`
	TimeoutMs   int32          `json:"timeout_ms"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateNameserver(ctx context.Context, arg CreateNameserverParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNameserver,
		arg.Name,
		arg.Type,
		arg.Server,
		arg.Port,
		arg.TimeoutMs,
		arg.Enabled,
		arg.Description,
	)
}

const deleteNameserver = `-- name: DeleteNameserver :exec
DELETE FROM nameservers WHERE id = ?
`

func (q *Queries) DeleteNameserver(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNameserver, id)
	return err
}

const getNameserverByID = `-- name: GetNameserverByID :one
SELECT id, name, type, server, port, timeout_ms, enabled, description, created_at, updated_at FROM nameservers WHERE id = ?
`

func (q *Queries) GetNameserverByID(ctx context.Context, id int64) (Nameserver, error) {
	row := q.db.QueryRowContext(ctx, getNameserverByID, id)
	var i Nameserver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Server,
		&i.Port,
		&i.TimeoutMs,
		&i.Enabled,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNameservers = `-- name: ListNameservers :many
SELECT id, name, type, server, port, timeout_ms, enabled, description, created_at, updated_at FROM nameservers ORDER BY name LIMIT ? OFFSET ?
`

type ListNameserversParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNameservers(ctx context.Context, arg ListNameserversParams) ([]Nameserver, error) {
	rows, err := q.db.QueryContext(ctx, listNameservers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Nameserver{}
	for rows.Next() {
		var i Nameserver
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Server,
			&i.Port,
			&i.TimeoutMs,
			&i.Enabled,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNameserver = `-- name: UpdateNameserver :exec
UPDATE nameservers SET name = ?, type = ?, server = ?, port = ?, timeout_ms = ?, enabled = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateNameserverParams struct {
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Server      string         `json:"server"`
	Port        int32          `json:"port"`
	TimeoutMs   int32          `json:"timeout_ms"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateNameserver(ctx context.Context, arg UpdateNameserverParams) error {
	_, err := q.db.ExecContext(ctx, updateNameserver,
		arg.Name,
		arg.Type,
		arg.Server,
		arg.Port,
		arg.TimeoutMs,
		arg.Enabled,
		arg.Description,
		arg.ID,
	)
	return err
}
