// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nats.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countNats = `-- name: CountNats :one
SELECT COUNT(*) FROM nats
`

func (q *Queries) CountNats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNat = `-- name: CreateNat :execresult
INSERT INTO nats (name, type, inside_address_id, outside_address_id, inside_ip, outside_ip, inside_port, outside_port, protocol, device_id, description, enabled) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNatParams struct {
	Name             string         `json:"name"`
	Type             string         `json:"type"`
	InsideAddressID  sql.NullInt64  `json:"inside_address_id"`
	OutsideAddressID sql.NullInt64  `json:"outside_address_id"`
	InsideIp         string         `json:"inside_ip"`
	OutsideIp        string         `json:"outside_ip"`
	InsidePort       sql.NullInt32  `json:"inside_port"`
	OutsidePort      sql.NullInt32  `json:"outside_port"`
	Protocol         string         `json:"protocol"`
	DeviceID         sql.NullInt64  `json:"device_id"`
	Description      sql.NullString `json:"description"`
	Enabled          bool           `json:"enabled"`
}

func (q *Queries) CreateNat(ctx context.Context, arg CreateNatParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNat,
		arg.Name,
		arg.Type,
		arg.InsideAddressID,
		arg.OutsideAddressID,
		arg.InsideIp,
		arg.OutsideIp,
		arg.InsidePort,
		arg.OutsidePort,
		arg.Protocol,
		arg.DeviceID,
		arg.Description,
		arg.Enabled,
	)
}

const deleteNat = `-- name: DeleteNat :exec
DELETE FROM nats WHERE id = ?
`

func (q *Queries) DeleteNat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNat, id)
	return err
}

const getNatByID = `-- name: GetNatByID :one
SELECT id, name, type, inside_address_id, outside_address_id, inside_ip, outside_ip, inside_port, outside_port, protocol, device_id, description, enabled, created_at, updated_at FROM nats WHERE id = ?
`

func (q *Queries) GetNatByID(ctx context.Context, id int64) (Nat, error) {
	row := q.db.QueryRowContext(ctx, getNatByID, id)
	var i Nat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.InsideAddressID,
		&i.OutsideAddressID,
		&i.InsideIp,
		&i.OutsideIp,
		&i.InsidePort,
		&i.OutsidePort,
		&i.Protocol,
		&i.DeviceID,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNats = `-- name: ListNats :many
SELECT id, name, type, inside_address_id, outside_address_id, inside_ip, outside_ip, inside_port, outside_port, protocol, device_id, description, enabled, created_at, updated_at FROM nats ORDER BY name LIMIT ? OFFSET ?
`

type ListNatsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNats(ctx context.Context, arg ListNatsParams) ([]Nat, error) {
	rows, err := q.db.QueryContext(ctx, listNats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Nat{}
	for rows.Next() {
		var i Nat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.InsideAddressID,
			&i.OutsideAddressID,
			&i.InsideIp,
			&i.OutsideIp,
			&i.InsidePort,
			&i.OutsidePort,
			&i.Protocol,
			&i.DeviceID,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNat = `-- name: UpdateNat :exec
UPDATE nats SET name = ?, type = ?, inside_address_id = ?, outside_address_id = ?, inside_ip = ?, outside_ip = ?, inside_port = ?, outside_port = ?, protocol = ?, device_id = ?, description = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateNatParams struct {
	Name             string         `json:"name"`
	Type             string         `json:"type"`
	InsideAddressID  sql.NullInt64  `json:"inside_address_id"`
	OutsideAddressID sql.NullInt64  `json:"outside_address_id"`
	InsideIp         string         `json:"inside_ip"`
	OutsideIp        string         `json:"outside_ip"`
	InsidePort       sql.NullInt32  `json:"inside_port"`
	OutsidePort      sql.NullInt32  `json:"outside_port"`
	Protocol         string         `json:"protocol"`
	DeviceID         sql.NullInt64  `json:"device_id"`
	Description      sql.NullString `json:"description"`
	Enabled          bool           `json:"enabled"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateNat(ctx context.Context, arg UpdateNatParams) error {
	_, err := q.db.ExecContext(ctx, updateNat,
		arg.Name,
		arg.Type,
		arg.InsideAddressID,
		arg.OutsideAddressID,
		arg.InsideIp,
		arg.OutsideIp,
		arg.InsidePort,
		arg.OutsidePort,
		arg.Protocol,
		arg.DeviceID,
		arg.Description,
		arg.Enabled,
		arg.ID,
	)
	return err
}
