// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddGroupRole(ctx context.Context, arg AddGroupRoleParams) error
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	CountAddresses(ctx context.Context, subnetID int64) (int64, error)
	CountAddressesByStatus(ctx context.Context, arg CountAddressesByStatusParams) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountDevices(ctx context.Context) (int64, error)
	CountFolders(ctx context.Context, sectionID int64) (int64, error)
	CountIPRequests(ctx context.Context) (int64, error)
	CountL2Domains(ctx context.Context) (int64, error)
	CountLocations(ctx context.Context) (int64, error)
	CountNameservers(ctx context.Context) (int64, error)
	CountNats(ctx context.Context) (int64, error)
	CountRacks(ctx context.Context, locationID int64) (int64, error)
	CountScanTasks(ctx context.Context) (int64, error)
	CountSections(ctx context.Context) (int64, error)
	CountSubnets(ctx context.Context, sectionID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVlans(ctx context.Context) (int64, error)
	CountVrfs(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (sql.Result, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (sql.Result, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (sql.Result, error)
	CreateDeviceType(ctx context.Context, arg CreateDeviceTypeParams) (sql.Result, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (sql.Result, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error)
	CreateIPRequest(ctx context.Context, arg CreateIPRequestParams) (sql.Result, error)
	CreateL2Domain(ctx context.Context, arg CreateL2DomainParams) (sql.Result, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (sql.Result, error)
	CreateNameserver(ctx context.Context, arg CreateNameserverParams) (sql.Result, error)
	CreateNat(ctx context.Context, arg CreateNatParams) (sql.Result, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (sql.Result, error)
	CreateRack(ctx context.Context, arg CreateRackParams) (sql.Result, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error)
	CreateScanResult(ctx context.Context, arg CreateScanResultParams) (sql.Result, error)
	CreateScanTask(ctx context.Context, arg CreateScanTaskParams) (sql.Result, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (sql.Result, error)
	CreateSubnet(ctx context.Context, arg CreateSubnetParams) (sql.Result, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateVlan(ctx context.Context, arg CreateVlanParams) (sql.Result, error)
	CreateVrf(ctx context.Context, arg CreateVrfParams) (sql.Result, error)
	DeleteAPIToken(ctx context.Context, id int64) error
	DeleteAddress(ctx context.Context, id int64) error
	DeleteDevice(ctx context.Context, id int64) error
	DeleteDeviceType(ctx context.Context, id int64) error
	DeleteFolder(ctx context.Context, id int64) error
	DeleteGroup(ctx context.Context, id int64) error
	DeleteIPRequest(ctx context.Context, id int64) error
	DeleteL2Domain(ctx context.Context, id int64) error
	DeleteLocation(ctx context.Context, id int64) error
	DeleteNameserver(ctx context.Context, id int64) error
	DeleteNat(ctx context.Context, id int64) error
	DeleteRack(ctx context.Context, id int64) error
	DeleteResourcePermission(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteScanTask(ctx context.Context, id int64) error
	DeleteSection(ctx context.Context, id int64) error
	DeleteSubnet(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteVlan(ctx context.Context, id int64) error
	DeleteVrf(ctx context.Context, id int64) error
	FindOverlappingSubnets(ctx context.Context, arg FindOverlappingSubnetsParams) ([]Subnet, error)
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAddressByID(ctx context.Context, id int64) (Address, error)
	GetAddressByIP(ctx context.Context, arg GetAddressByIPParams) (Address, error)
	GetAddressByIPText(ctx context.Context, arg GetAddressByIPTextParams) (Address, error)
	GetChildSubnets(ctx context.Context, parentID sql.NullInt64) ([]Subnet, error)
	GetDeviceByID(ctx context.Context, id int64) (Device, error)
	GetDeviceTypeByID(ctx context.Context, id int64) (DeviceType, error)
	GetFolderByID(ctx context.Context, id int64) (Folder, error)
	GetGroupByID(ctx context.Context, id int64) (Group, error)
	GetGroupRoles(ctx context.Context, groupID int64) ([]Role, error)
	GetIPRequestByID(ctx context.Context, id int64) (IpRequest, error)
	GetL2DomainByID(ctx context.Context, id int64) (L2Domain, error)
	GetLocationByID(ctx context.Context, id int64) (Location, error)
	GetNameserverByID(ctx context.Context, id int64) (Nameserver, error)
	GetNatByID(ctx context.Context, id int64) (Nat, error)
	GetPermissionByCode(ctx context.Context, code string) (Permission, error)
	GetRackByID(ctx context.Context, id int64) (Rack, error)
	GetResourcePermissions(ctx context.Context, arg GetResourcePermissionsParams) ([]ResourcePermission, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRolePermissions(ctx context.Context, roleID int64) ([]Permission, error)
	GetScanResults(ctx context.Context, taskID int64) ([]ScanResult, error)
	GetScanTaskByID(ctx context.Context, id int64) (ScanTask, error)
	GetSectionByID(ctx context.Context, id int64) (Section, error)
	GetSubFolders(ctx context.Context, parentID sql.NullInt64) ([]Folder, error)
	GetSubSections(ctx context.Context, parentID sql.NullInt64) ([]Section, error)
	GetSubnetByID(ctx context.Context, id int64) (Subnet, error)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserGroups(ctx context.Context, userID int64) ([]Group, error)
	GetUserResourcePermissions(ctx context.Context, userID sql.NullInt64) ([]ResourcePermission, error)
	GetUserRoles(ctx context.Context, userID int64) ([]Role, error)
	GetVlanByID(ctx context.Context, id int64) (Vlan, error)
	GetVrfByID(ctx context.Context, id int64) (Vrf, error)
	ListAPITokens(ctx context.Context, userID int64) ([]ListAPITokensRow, error)
	ListAddressIPsBySubnet(ctx context.Context, subnetID int64) ([]string, error)
	ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListDeviceTypes(ctx context.Context) ([]DeviceType, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListIPRequests(ctx context.Context, arg ListIPRequestsParams) ([]IpRequest, error)
	ListL2Domains(ctx context.Context, arg ListL2DomainsParams) ([]L2Domain, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error)
	ListNameservers(ctx context.Context, arg ListNameserversParams) ([]Nameserver, error)
	ListNats(ctx context.Context, arg ListNatsParams) ([]Nat, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRacks(ctx context.Context, arg ListRacksParams) ([]Rack, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListScanTasks(ctx context.Context, arg ListScanTasksParams) ([]ScanTask, error)
	ListSections(ctx context.Context, arg ListSectionsParams) ([]Section, error)
	ListSubnets(ctx context.Context, arg ListSubnetsParams) ([]Subnet, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVlans(ctx context.Context, arg ListVlansParams) ([]Vlan, error)
	ListVrfs(ctx context.Context, arg ListVrfsParams) ([]Vrf, error)
	RemoveGroupRole(ctx context.Context, arg RemoveGroupRoleParams) error
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	SearchAddresses(ctx context.Context, arg SearchAddressesParams) ([]Address, error)
	SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]Device, error)
	SearchSubnets(ctx context.Context, arg SearchSubnetsParams) ([]Subnet, error)
	SetResourcePermission(ctx context.Context, arg SetResourcePermissionParams) (sql.Result, error)
	UpdateAPITokenLastUsed(ctx context.Context, id int64) error
	UpdateAPITokenStatus(ctx context.Context, arg UpdateAPITokenStatusParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) error
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) error
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	UpdateIPRequestStatus(ctx context.Context, arg UpdateIPRequestStatusParams) error
	UpdateL2Domain(ctx context.Context, arg UpdateL2DomainParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) error
	UpdateNameserver(ctx context.Context, arg UpdateNameserverParams) error
	UpdateNat(ctx context.Context, arg UpdateNatParams) error
	UpdateRack(ctx context.Context, arg UpdateRackParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateScanTaskStatus(ctx context.Context, arg UpdateScanTaskStatusParams) error
	UpdateSection(ctx context.Context, arg UpdateSectionParams) error
	UpdateSubnet(ctx context.Context, arg UpdateSubnetParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserLoginInfo(ctx context.Context, arg UpdateUserLoginInfoParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVlan(ctx context.Context, arg UpdateVlanParams) error
	UpdateVrf(ctx context.Context, arg UpdateVrfParams) error
}

var _ Querier = (*Queries)(nil)
