// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countIPRequests = `-- name: CountIPRequests :one
SELECT COUNT(*) FROM ip_requests
`

func (q *Queries) CountIPRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIPRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIPRequest = `-- name: CreateIPRequest :execresult
INSERT INTO ip_requests (subnet_id, applicant_id, requested_ip, hostname, description, status) VALUES (?, ?, ?, ?, ?, 'pending')
`

type CreateIPRequestParams struct {
	SubnetID    int64          `json:"subnet_id"`
	ApplicantID int64          `json:"applicant_id"`
	RequestedIp string         `json:"requested_ip"`
	Hostname    string         `json:"hostname"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateIPRequest(ctx context.Context, arg CreateIPRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIPRequest,
		arg.SubnetID,
		arg.ApplicantID,
		arg.RequestedIp,
		arg.Hostname,
		arg.Description,
	)
}

const deleteIPRequest = `-- name: DeleteIPRequest :exec
DELETE FROM ip_requests WHERE id = ?
`

func (q *Queries) DeleteIPRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIPRequest, id)
	return err
}

const getIPRequestByID = `-- name: GetIPRequestByID :one
SELECT id, subnet_id, applicant_id, requested_ip, hostname, description, status, approver_id, approve_comment, created_at, updated_at FROM ip_requests WHERE id = ?
`

func (q *Queries) GetIPRequestByID(ctx context.Context, id int64) (IpRequest, error) {
	row := q.db.QueryRowContext(ctx, getIPRequestByID, id)
	var i IpRequest
	err := row.Scan(
		&i.ID,
		&i.SubnetID,
		&i.ApplicantID,
		&i.RequestedIp,
		&i.Hostname,
		&i.Description,
		&i.Status,
		&i.ApproverID,
		&i.ApproveComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIPRequests = `-- name: ListIPRequests :many
SELECT id, subnet_id, applicant_id, requested_ip, hostname, description, status, approver_id, approve_comment, created_at, updated_at FROM ip_requests ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListIPRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIPRequests(ctx context.Context, arg ListIPRequestsParams) ([]IpRequest, error) {
	rows, err := q.db.QueryContext(ctx, listIPRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IpRequest{}
	for rows.Next() {
		var i IpRequest
		if err := rows.Scan(
			&i.ID,
			&i.SubnetID,
			&i.ApplicantID,
			&i.RequestedIp,
			&i.Hostname,
			&i.Description,
			&i.Status,
			&i.ApproverID,
			&i.ApproveComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIPRequestStatus = `-- name: UpdateIPRequestStatus :exec
UPDATE ip_requests SET status = ?, approver_id = ?, approve_comment = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateIPRequestStatusParams struct {
	Status         string         `json:"status"`
	ApproverID     sql.NullInt64  `json:"approver_id"`
	ApproveComment sql.NullString `json:"approve_comment"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateIPRequestStatus(ctx context.Context, arg UpdateIPRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIPRequestStatus,
		arg.Status,
		arg.ApproverID,
		arg.ApproveComment,
		arg.ID,
	)
	return err
}
