// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countScanTasks = `-- name: CountScanTasks :one
SELECT COUNT(*) FROM scan_tasks
`

func (q *Queries) CountScanTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanResult = `-- name: CreateScanResult :execresult
INSERT INTO scan_results (task_id, ip_text, status, message) VALUES (?, ?, ?, ?)
`

type CreateScanResultParams struct {
	TaskID  int64          `json:"task_id"`
	IpText  string         `json:"ip_text"`
	Status  string         `json:"status"`
	Message sql.NullString `json:"message"`
}

func (q *Queries) CreateScanResult(ctx context.Context, arg CreateScanResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createScanResult,
		arg.TaskID,
		arg.IpText,
		arg.Status,
		arg.Message,
	)
}

const createScanTask = `-- name: CreateScanTask :execresult
INSERT INTO scan_tasks (subnet_id, task_type, status, total_count) VALUES (?, ?, 'pending', 0)
`

type CreateScanTaskParams struct {
	SubnetID int64  `json:"subnet_id"`
	TaskType string `json:"task_type"`
}

func (q *Queries) CreateScanTask(ctx context.Context, arg CreateScanTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createScanTask, arg.SubnetID, arg.TaskType)
}

const deleteScanTask = `-- name: DeleteScanTask :exec
DELETE FROM scan_tasks WHERE id = ?
`

func (q *Queries) DeleteScanTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScanTask, id)
	return err
}

const getScanResults = `-- name: GetScanResults :many
SELECT id, task_id, ip_text, status, message, created_at FROM scan_results WHERE task_id = ? ORDER BY ip_text
`

func (q *Queries) GetScanResults(ctx context.Context, taskID int64) ([]ScanResult, error) {
	rows, err := q.db.QueryContext(ctx, getScanResults, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanResult{}
	for rows.Next() {
		var i ScanResult
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.IpText,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanTaskByID = `-- name: GetScanTaskByID :one
SELECT id, subnet_id, task_type, status, started_at, finished_at, total_count, alive_count, new_count, error, created_at, updated_at FROM scan_tasks WHERE id = ?
`

func (q *Queries) GetScanTaskByID(ctx context.Context, id int64) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, getScanTaskByID, id)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.SubnetID,
		&i.TaskType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TotalCount,
		&i.AliveCount,
		&i.NewCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScanTasks = `-- name: ListScanTasks :many
SELECT id, subnet_id, task_type, status, started_at, finished_at, total_count, alive_count, new_count, error, created_at, updated_at FROM scan_tasks ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListScanTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScanTasks(ctx context.Context, arg ListScanTasksParams) ([]ScanTask, error) {
	rows, err := q.db.QueryContext(ctx, listScanTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTask{}
	for rows.Next() {
		var i ScanTask
		if err := rows.Scan(
			&i.ID,
			&i.SubnetID,
			&i.TaskType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TotalCount,
			&i.AliveCount,
			&i.NewCount,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanTaskStatus = `-- name: UpdateScanTaskStatus :exec
UPDATE scan_tasks SET status = ?, started_at = ?, finished_at = ?, alive_count = ?, new_count = ?, error = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateScanTaskStatusParams struct {
	Status     string         `json:"status"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
	AliveCount int32          `json:"alive_count"`
	NewCount   int32          `json:"new_count"`
	Error      sql.NullString `json:"error"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateScanTaskStatus(ctx context.Context, arg UpdateScanTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanTaskStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.AliveCount,
		arg.NewCount,
		arg.Error,
		arg.ID,
	)
	return err
}
