// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"
	"database/sql"
)

const searchAddresses = `-- name: SearchAddresses :many
SELECT id, subnet_id, ip, ip_text, hostname, mac, description, status, tag_id, is_gateway, device_id, device_port, owner, last_seen_at, dns_checked_at, created_at, updated_at FROM addresses WHERE hostname LIKE ? OR ip_text LIKE ? OR mac LIKE ? OR description LIKE ? LIMIT ? OFFSET ?
`

type SearchAddressesParams struct {
	Hostname    string         `json:"hostname"`
	IpText      string         `json:"ip_text"`
	Mac         string         `json:"mac"`
	Description sql.NullString `json:"description"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
}

func (q *Queries) SearchAddresses(ctx context.Context, arg SearchAddressesParams) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, searchAddresses,
		arg.Hostname,
		arg.IpText,
		arg.Mac,
		arg.Description,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.SubnetID,
			&i.Ip,
			&i.IpText,
			&i.Hostname,
			&i.Mac,
			&i.Description,
			&i.Status,
			&i.TagID,
			&i.IsGateway,
			&i.DeviceID,
			&i.DevicePort,
			&i.Owner,
			&i.LastSeenAt,
			&i.DnsCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDevices = `-- name: SearchDevices :many
SELECT id, name, hostname, mgmt_ip, type_id, location_id, rack_id, rack_start_u, rack_size_u, manufacturer, model, serial_number, description, created_at, updated_at FROM devices WHERE name LIKE ? OR hostname LIKE ? OR mgmt_ip LIKE ? LIMIT ?
`

type SearchDevicesParams struct {
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	MgmtIp   string `json:"mgmt_ip"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, searchDevices,
		arg.Name,
		arg.Hostname,
		arg.MgmtIp,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.MgmtIp,
			&i.TypeID,
			&i.LocationID,
			&i.RackID,
			&i.RackStartU,
			&i.RackSizeU,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNumber,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubnets = `-- name: SearchSubnets :many
SELECT id, section_id, parent_id, cidr, ip_version, network, prefix_len, name, description, vlan_id, vrf_id, location_id, nameserver_id, scan_enabled, discover_enabled, threshold_percent, allow_request, status, created_at, updated_at FROM subnets WHERE name LIKE ? OR cidr LIKE ? OR description LIKE ? LIMIT ?
`

type SearchSubnetsParams struct {
	Name        string         `json:"name"`
	Cidr        string         `json:"cidr"`
	Description sql.NullString `json:"description"`
	Limit       int32          `json:"limit"`
}

func (q *Queries) SearchSubnets(ctx context.Context, arg SearchSubnetsParams) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, searchSubnets,
		arg.Name,
		arg.Cidr,
		arg.Description,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ParentID,
			&i.Cidr,
			&i.IpVersion,
			&i.Network,
			&i.PrefixLen,
			&i.Name,
			&i.Description,
			&i.VlanID,
			&i.VrfID,
			&i.LocationID,
			&i.NameserverID,
			&i.ScanEnabled,
			&i.DiscoverEnabled,
			&i.ThresholdPercent,
			&i.AllowRequest,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
