// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sections.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countSections = `-- name: CountSections :one
SELECT COUNT(*) FROM sections
`

func (q *Queries) CountSections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSection = `-- name: CreateSection :execresult
INSERT INTO sections (name, description, parent_id, strict_mode, show_vlan, show_vrf, subnet_order, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSectionParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	StrictMode  bool           `json:"strict_mode"`
	ShowVlan    bool           `json:"show_vlan"`
	ShowVrf     bool           `json:"show_vrf"`
	SubnetOrder string         `json:"subnet_order"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSection,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.StrictMode,
		arg.ShowVlan,
		arg.ShowVrf,
		arg.SubnetOrder,
		arg.SortOrder,
	)
}

const deleteSection = `-- name: DeleteSection :exec
DELETE FROM sections WHERE id = ?
`

func (q *Queries) DeleteSection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSection, id)
	return err
}

const getSectionByID = `-- name: GetSectionByID :one
SELECT id, name, description, parent_id, strict_mode, show_vlan, show_vrf, subnet_order, sort_order, created_at, updated_at
FROM sections
WHERE id = ?
`

func (q *Queries) GetSectionByID(ctx context.Context, id int64) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSectionByID, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.StrictMode,
		&i.ShowVlan,
		&i.ShowVrf,
		&i.SubnetOrder,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubSections = `-- name: GetSubSections :many
SELECT id, name, description, parent_id, strict_mode, show_vlan, show_vrf, subnet_order, sort_order, created_at, updated_at
FROM sections
WHERE parent_id = ?
ORDER BY sort_order, name
`

func (q *Queries) GetSubSections(ctx context.Context, parentID sql.NullInt64) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, getSubSections, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.StrictMode,
			&i.ShowVlan,
			&i.ShowVrf,
			&i.SubnetOrder,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT id, name, description, parent_id, strict_mode, show_vlan, show_vrf, subnet_order, sort_order, created_at, updated_at
FROM sections
ORDER BY sort_order, name
LIMIT ? OFFSET ?
`

type ListSectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSections(ctx context.Context, arg ListSectionsParams) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.StrictMode,
			&i.ShowVlan,
			&i.ShowVrf,
			&i.SubnetOrder,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :exec
UPDATE sections
SET name = ?, description = ?, parent_id = ?, strict_mode = ?, show_vlan = ?, show_vrf = ?, subnet_order = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSectionParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	StrictMode  bool           `json:"strict_mode"`
	ShowVlan    bool           `json:"show_vlan"`
	ShowVrf     bool           `json:"show_vrf"`
	SubnetOrder string         `json:"subnet_order"`
	SortOrder   int32          `json:"sort_order"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) error {
	_, err := q.db.ExecContext(ctx, updateSection,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.StrictMode,
		arg.ShowVlan,
		arg.ShowVrf,
		arg.SubnetOrder,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
