// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subnets.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countSubnets = `-- name: CountSubnets :one
SELECT COUNT(*) FROM subnets WHERE section_id = ?
`

func (q *Queries) CountSubnets(ctx context.Context, sectionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubnets, sectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubnet = `-- name: CreateSubnet :execresult
INSERT INTO subnets (section_id, parent_id, cidr, ip_version, network, prefix_len, name, description, vlan_id, vrf_id, location_id, nameserver_id, scan_enabled, discover_enabled, threshold_percent, allow_request, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSubnetParams struct {
	SectionID        int64          `json:"section_id"`
	ParentID         sql.NullInt64  `json:"parent_id"`
	Cidr             string         `json:"cidr"`
	IpVersion        uint8          `json:"ip_version"`
	Network          []byte         `json:"network"`
	PrefixLen        uint8          `json:"prefix_len"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	VlanID           sql.NullInt64  `json:"vlan_id"`
	VrfID            sql.NullInt64  `json:"vrf_id"`
	LocationID       sql.NullInt64  `json:"location_id"`
	NameserverID     sql.NullInt64  `json:"nameserver_id"`
	ScanEnabled      bool           `json:"scan_enabled"`
	DiscoverEnabled  bool           `json:"discover_enabled"`
	ThresholdPercent int32          `json:"threshold_percent"`
	AllowRequest     bool           `json:"allow_request"`
	Status           string         `json:"status"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSubnet,
		arg.SectionID,
		arg.ParentID,
		arg.Cidr,
		arg.IpVersion,
		arg.Network,
		arg.PrefixLen,
		arg.Name,
		arg.Description,
		arg.VlanID,
		arg.VrfID,
		arg.LocationID,
		arg.NameserverID,
		arg.ScanEnabled,
		arg.DiscoverEnabled,
		arg.ThresholdPercent,
		arg.AllowRequest,
		arg.Status,
	)
}

const deleteSubnet = `-- name: DeleteSubnet :exec
DELETE FROM subnets WHERE id = ?
`

func (q *Queries) DeleteSubnet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubnet, id)
	return err
}

const findOverlappingSubnets = `-- name: FindOverlappingSubnets :many
SELECT id, section_id, parent_id, cidr, ip_version, network, prefix_len, name, description, vlan_id, vrf_id, location_id, nameserver_id, scan_enabled, discover_enabled, threshold_percent, allow_request, status, created_at, updated_at
FROM subnets
WHERE section_id = ? AND (vrf_id = ? OR (? IS NULL AND vrf_id IS NULL)) AND id != ?
`

type FindOverlappingSubnetsParams struct {
	SectionID int64         `json:"section_id"`
	VrfID     sql.NullInt64 `json:"vrf_id"`
	ID        int64         `json:"id"`
}

func (q *Queries) FindOverlappingSubnets(ctx context.Context, arg FindOverlappingSubnetsParams) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, findOverlappingSubnets,
		arg.SectionID,
		arg.VrfID,
		arg.VrfID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ParentID,
			&i.Cidr,
			&i.IpVersion,
			&i.Network,
			&i.PrefixLen,
			&i.Name,
			&i.Description,
			&i.VlanID,
			&i.VrfID,
			&i.LocationID,
			&i.NameserverID,
			&i.ScanEnabled,
			&i.DiscoverEnabled,
			&i.ThresholdPercent,
			&i.AllowRequest,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildSubnets = `-- name: GetChildSubnets :many
SELECT id, section_id, parent_id, cidr, ip_version, network, prefix_len, name, description, vlan_id, vrf_id, location_id, nameserver_id, scan_enabled, discover_enabled, threshold_percent, allow_request, status, created_at, updated_at
FROM subnets
WHERE parent_id = ?
ORDER BY network
`

func (q *Queries) GetChildSubnets(ctx context.Context, parentID sql.NullInt64) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getChildSubnets, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ParentID,
			&i.Cidr,
			&i.IpVersion,
			&i.Network,
			&i.PrefixLen,
			&i.Name,
			&i.Description,
			&i.VlanID,
			&i.VrfID,
			&i.LocationID,
			&i.NameserverID,
			&i.ScanEnabled,
			&i.DiscoverEnabled,
			&i.ThresholdPercent,
			&i.AllowRequest,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubnetByID = `-- name: GetSubnetByID :one
SELECT id, section_id, parent_id, cidr, ip_version, network, prefix_len, name, description, vlan_id, vrf_id, location_id, nameserver_id, scan_enabled, discover_enabled, threshold_percent, allow_request, status, created_at, updated_at
FROM subnets
WHERE id = ?
`

func (q *Queries) GetSubnetByID(ctx context.Context, id int64) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByID, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.ParentID,
		&i.Cidr,
		&i.IpVersion,
		&i.Network,
		&i.PrefixLen,
		&i.Name,
		&i.Description,
		&i.VlanID,
		&i.VrfID,
		&i.LocationID,
		&i.NameserverID,
		&i.ScanEnabled,
		&i.DiscoverEnabled,
		&i.ThresholdPercent,
		&i.AllowRequest,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, section_id, parent_id, cidr, ip_version, network, prefix_len, name, description, vlan_id, vrf_id, location_id, nameserver_id, scan_enabled, discover_enabled, threshold_percent, allow_request, status, created_at, updated_at
FROM subnets
WHERE section_id = ?
ORDER BY network
LIMIT ? OFFSET ?
`

type ListSubnetsParams struct {
	SectionID int64 `json:"section_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListSubnets(ctx context.Context, arg ListSubnetsParams) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnets, arg.SectionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.ParentID,
			&i.Cidr,
			&i.IpVersion,
			&i.Network,
			&i.PrefixLen,
			&i.Name,
			&i.Description,
			&i.VlanID,
			&i.VrfID,
			&i.LocationID,
			&i.NameserverID,
			&i.ScanEnabled,
			&i.DiscoverEnabled,
			&i.ThresholdPercent,
			&i.AllowRequest,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubnet = `-- name: UpdateSubnet :exec
UPDATE subnets
SET name = ?, description = ?, vlan_id = ?, vrf_id = ?, location_id = ?, nameserver_id = ?, scan_enabled = ?, discover_enabled = ?, threshold_percent = ?, allow_request = ?, status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSubnetParams struct {
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	VlanID           sql.NullInt64  `json:"vlan_id"`
	VrfID            sql.NullInt64  `json:"vrf_id"`
	LocationID       sql.NullInt64  `json:"location_id"`
	NameserverID     sql.NullInt64  `json:"nameserver_id"`
	ScanEnabled      bool           `json:"scan_enabled"`
	DiscoverEnabled  bool           `json:"discover_enabled"`
	ThresholdPercent int32          `json:"threshold_percent"`
	AllowRequest     bool           `json:"allow_request"`
	Status           string         `json:"status"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateSubnet(ctx context.Context, arg UpdateSubnetParams) error {
	_, err := q.db.ExecContext(ctx, updateSubnet,
		arg.Name,
		arg.Description,
		arg.VlanID,
		arg.VrfID,
		arg.LocationID,
		arg.NameserverID,
		arg.ScanEnabled,
		arg.DiscoverEnabled,
		arg.ThresholdPercent,
		arg.AllowRequest,
		arg.Status,
		arg.ID,
	)
	return err
}
