// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vlans.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countL2Domains = `-- name: CountL2Domains :one
SELECT COUNT(*) FROM l2_domains
`

func (q *Queries) CountL2Domains(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countL2Domains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVlans = `-- name: CountVlans :one
SELECT COUNT(*) FROM vlans
`

func (q *Queries) CountVlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createL2Domain = `-- name: CreateL2Domain :execresult
INSERT INTO l2_domains (name, description) VALUES (?, ?)
`

type CreateL2DomainParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateL2Domain(ctx context.Context, arg CreateL2DomainParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createL2Domain, arg.Name, arg.Description)
}

const createVlan = `-- name: CreateVlan :execresult
INSERT INTO vlans (l2_domain_id, vlan_id, name, description) VALUES (?, ?, ?, ?)
`

type CreateVlanParams struct {
	L2DomainID  sql.NullInt64  `json:"l2_domain_id"`
	VlanID      int32          `json:"vlan_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateVlan(ctx context.Context, arg CreateVlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVlan,
		arg.L2DomainID,
		arg.VlanID,
		arg.Name,
		arg.Description,
	)
}

const deleteL2Domain = `-- name: DeleteL2Domain :exec
DELETE FROM l2_domains WHERE id = ?
`

func (q *Queries) DeleteL2Domain(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteL2Domain, id)
	return err
}

const deleteVlan = `-- name: DeleteVlan :exec
DELETE FROM vlans WHERE id = ?
`

func (q *Queries) DeleteVlan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVlan, id)
	return err
}

const getL2DomainByID = `-- name: GetL2DomainByID :one
SELECT id, name, description, created_at, updated_at FROM l2_domains WHERE id = ?
`

func (q *Queries) GetL2DomainByID(ctx context.Context, id int64) (L2Domain, error) {
	row := q.db.QueryRowContext(ctx, getL2DomainByID, id)
	var i L2Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVlanByID = `-- name: GetVlanByID :one
SELECT id, l2_domain_id, vlan_id, name, description, created_at, updated_at FROM vlans WHERE id = ?
`

func (q *Queries) GetVlanByID(ctx context.Context, id int64) (Vlan, error) {
	row := q.db.QueryRowContext(ctx, getVlanByID, id)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.L2DomainID,
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listL2Domains = `-- name: ListL2Domains :many
SELECT id, name, description, created_at, updated_at FROM l2_domains ORDER BY name LIMIT ? OFFSET ?
`

type ListL2DomainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListL2Domains(ctx context.Context, arg ListL2DomainsParams) ([]L2Domain, error) {
	rows, err := q.db.QueryContext(ctx, listL2Domains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []L2Domain{}
	for rows.Next() {
		var i L2Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVlans = `-- name: ListVlans :many
SELECT id, l2_domain_id, vlan_id, name, description, created_at, updated_at FROM vlans ORDER BY vlan_id LIMIT ? OFFSET ?
`

type ListVlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVlans(ctx context.Context, arg ListVlansParams) ([]Vlan, error) {
	rows, err := q.db.QueryContext(ctx, listVlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vlan{}
	for rows.Next() {
		var i Vlan
		if err := rows.Scan(
			&i.ID,
			&i.L2DomainID,
			&i.VlanID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateL2Domain = `-- name: UpdateL2Domain :exec
UPDATE l2_domains SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateL2DomainParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateL2Domain(ctx context.Context, arg UpdateL2DomainParams) error {
	_, err := q.db.ExecContext(ctx, updateL2Domain, arg.Name, arg.Description, arg.ID)
	return err
}

const updateVlan = `-- name: UpdateVlan :exec
UPDATE vlans SET l2_domain_id = ?, vlan_id = ?, name = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVlanParams struct {
	L2DomainID  sql.NullInt64  `json:"l2_domain_id"`
	VlanID      int32          `json:"vlan_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateVlan(ctx context.Context, arg UpdateVlanParams) error {
	_, err := q.db.ExecContext(ctx, updateVlan,
		arg.L2DomainID,
		arg.VlanID,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	return err
}
