// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vrfs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countVrfs = `-- name: CountVrfs :one
SELECT COUNT(*) FROM vrfs
`

func (q *Queries) CountVrfs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVrfs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVrf = `-- name: CreateVrf :execresult
INSERT INTO vrfs (name, rd, description) VALUES (?, ?, ?)
`

type CreateVrfParams struct {
	Name        string         `json:"name"`
	Rd          string         `json:"rd"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateVrf(ctx context.Context, arg CreateVrfParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVrf, arg.Name, arg.Rd, arg.Description)
}

const deleteVrf = `-- name: DeleteVrf :exec
DELETE FROM vrfs WHERE id = ?
`

func (q *Queries) DeleteVrf(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVrf, id)
	return err
}

const getVrfByID = `-- name: GetVrfByID :one
SELECT id, name, rd, description, created_at, updated_at FROM vrfs WHERE id = ?
`

func (q *Queries) GetVrfByID(ctx context.Context, id int64) (Vrf, error) {
	row := q.db.QueryRowContext(ctx, getVrfByID, id)
	var i Vrf
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rd,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVrfs = `-- name: ListVrfs :many
SELECT id, name, rd, description, created_at, updated_at FROM vrfs ORDER BY name LIMIT ? OFFSET ?
`

type ListVrfsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVrfs(ctx context.Context, arg ListVrfsParams) ([]Vrf, error) {
	rows, err := q.db.QueryContext(ctx, listVrfs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vrf{}
	for rows.Next() {
		var i Vrf
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rd,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVrf = `-- name: UpdateVrf :exec
UPDATE vrfs SET name = ?, rd = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVrfParams struct {
	Name        string         `json:"name"`
	Rd          string         `json:"rd"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateVrf(ctx context.Context, arg UpdateVrfParams) error {
	_, err := q.db.ExecContext(ctx, updateVrf,
		arg.Name,
		arg.Rd,
		arg.Description,
		arg.ID,
	)
	return err
}
