-- +goose Up
CREATE TABLE IF NOT EXISTS nameservers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(32) NOT NULL DEFAULT 'udp',
    server VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL DEFAULT 53,
    timeout_ms INTEGER NOT NULL DEFAULT 2000,
    enabled BOOLEAN NOT NULL DEFAULT 1,
    description TEXT NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS nameservers;
